# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  
  config.vm.synced_folder "../", "/svcDASHmuxer"
  config.vm.provision :shell, path: "provision.sh"
  config.vm.provision :shell, path: "provision_user.sh", privileged: false
end
